version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -F anything
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=project_db
    volumes:
      - .dbdata/db:/var/lib/postgresql/data
    ports:
      - 54320:5432
